# Site settings
title: Jmeas
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jmeas.com" # the base hostname & protocol for your site
github_username: jmeas

exclude: ['node_modules', 'css/stylus']

# Blog Settings
permalink: /blog/:year/:month/:day/:title
paginate: 1

plugins:
  - jekyll-paginate
